version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: olymp_mysql_57
    restart: always
    environment:
      MYSQL_DATABASE: tat_olymp
      MYSQL_ROOT_PASSWORD: 6yhn^YHN
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
